site_name: Spatial Computing Project Template

nav:
  - Home: "index.md"
  - Planning: 
      - Process: "a1_planning_process.md"
      - Product: "a1_planning_product.md"
  - Configuring: 
      - Process: "a2_configuring_process.md"
      - Product: "a2_configuring_product.md"
  - Massing:
      - Process: "a3_massing_process.md"
      - Product: "a3_massing_product.md"
  - Forming: 
      - Process: "a4_forming_process.md"
      - Product: "a4_forming_product.md"
  - About: "about.md"
  - Index:
      - Scripts: "index/scripts.md"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Notebooks:
    - Solar notebook: Notebooks/solar_studies.ipynb
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"

markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji

plugins:
  - mknotebooks
