site_name: Spatial Computing Project Template

nav:
  - Home: "index.md"
  - Planning: 
      - Process: "a1_planning_process.md"
      - Product: "a1_planning_product.md"
  - Configuring: 
      - Process: "a2_configuring_process.md"
      - Product: "a2_configuring_product.md"
  - Massing:
      - Process: "a3_massing_process.md"
      - Product: "a3_massing_product.md"
  - Forming: 
      - Process: "a4_forming_process.md"
      - Product: "a4_forming_product.md"
  - Reflection: "a5_reflection.md"
  - About: "about.md"
  - Index:
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"

  - Notebooks:
    - Voxelize notebook: Notebooks/_Voxelize notebook.ipynb
    - Solar studies notebook: Notebooks/_Solar studies notebook.ipynb
    - Facade closeness notebook: Notebooks/_Facade closeness notebook.ipynb
    - Floor closeness notebook: Notebooks/_Floor closeness notebook.ipynb
    - Entrance closeness notebook: Notebooks/_Entrance closeness notebook.ipynb
    - Quietness notebook: Notebooks/_Quietness notebook.ipynb
    - MCDA growth & shafts and corridors notebook: Notebooks/_MCDA growth & shafts and corridors notebook.ipynb
    - Forming facade notebook: Notebook/_Forming facade notebook.ipynb


theme:
  name: "material"

markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji

plugins:
  - mknotebooks
